### ISSUE TITLE
Add .navbar component

### ISSUE THREAD

**Issue by Kcchouette** [siimple/siimple#12]
Hello, thank you for this small CSS framework!

I want to know: is there a way to add a simple navbar (like that but more simpler, of course: http://bootsnipp.com/snippets/featured/navbar-search-add-on-bs-3 ) in Siimple CSS?

Or is there a way to have a invisible navbar menu which can collaspe for mobile?

Thank you.

**Comment by jmjuanes** [comment]
Hello @Kcchouette , thank you for using it!! 😄 

Currently I am working on this feature, a set of layout elements like navbars, jumbotrons, etc... But I don't know when it will be finished. If you like, I will notice you when these elements are ready to use. 

Thanks again for your interest!

**Comment by ChinuxParibus** [comment]
I'm really interested too, I forked the project yet and I'm interested in collaborate with those components
I'm using Siimple massively on my academic/production front-end projects :)
Greetings from Venezuela

**Comment by Kcchouette** [comment]
@jmjuanes yes, notice me, please. Thanks

**Comment by pawelotto** [comment]
Would be very nice to see that feature. Siimple is awesome!

**Comment by jmjuanes** [comment]
Hello! I just published the new v2.0.0 🎉 🎉 

The layout framework (which will include the navbar element) will be published soon on this repository: https://github.com/siimple/siimple-layout , so please if you have any questions or want to help/collaborate, open a new issue on the layout repository. 

Thank you! 😄
