### ISSUE TITLE
hosted on jsdelivr

### ISSUE THREAD

**Issue by gswalden** [siimple/siimple#14]
I like this library so much I submitted it to [jsdelivr.com](https://www.jsdelivr.com) ([pull request](https://github.com/jsdelivr/jsdelivr/pull/15433/files)). I'm not sure how long their system needs from merge to production, but hopefully not too long.

https://www.jsdelivr.com/projects/siimple should be the URL when it's live.

**Comment by jmjuanes** [comment]
Hi @gswalden 

Thanks a lot for submitting @siimple to jsDelivr!!! 😄 

I am working on the version 2.0.0. I think that the next week will be available, with a redesigned and minimal flat style.
