### ISSUE TITLE
font-size unit

### ISSUE THREAD

**Issue by wtser** [siimple/siimple#2]
![image](https://cloud.githubusercontent.com/assets/2093743/13101631/2798ecc2-d583-11e5-98ee-258fd8dc11bd.png)

![image](https://cloud.githubusercontent.com/assets/2093743/13101637/3329979e-d583-11e5-8d4a-9ff4cc1f4b68.png)

![image](https://cloud.githubusercontent.com/assets/2093743/13101647/4130c3d0-d583-11e5-8daa-d229889a399f.png)

**Comment by jmjuanes** [comment]
Hi @wtser, bug fixed on `v1.3.1`. Thanks!
