### ISSUE TITLE
Browser support ?

### ISSUE THREAD

**Issue by goriunov** [siimple/siimple#20]
Hello, hope your are having a great day, i am thinking to use this framework for my next project. I am just wondering about browser support. Which browsers this framework supports ?

Thank you

**Comment by goriunov** [comment]
Is it possible to add Browser support in README i think it would help a lot )

**Comment by jmjuanes** [comment]
Hi, thanks for your issue! 

**siimple-core** supports the latest/stable releases of all major browsers and platforms. I have tested it on Windows, Mac and Linux (Ubuntu), and it works well (Internet Explorer 10/11 too).

Thanks for your suggestion. I will add a table with the browser support in the README and in the new documentation site (currently is on development).

I hope you use it in your next project! If you have any problems or questions I will be pleased to help you 😄
