### ISSUE TITLE
Change containers sizes for mobile?

### ISSUE THREAD

**Issue by goriunov** [siimple/siimple#21]
I know that you can set responsive grid like 

`<div class="siimple-grid-col siimple-grid-col--5">my content</div>`

but what if in case i want only on mobiles it to be 12

`<div class="siimple-grid-col siimple-grid-col--12">My content</div>`

is there way to do it?

**Comment by jmjuanes** [comment]
Hi @goriunov 
I don't understand your question. On mobiles (or when the screen with is lower than 480px) all columns will change its width to 100%: 

![image](https://user-images.githubusercontent.com/5751201/30512926-374cc2fe-9afa-11e7-8e33-2112b73367a4.png)

![image](https://user-images.githubusercontent.com/5751201/30512937-54a7d2d0-9afa-11e7-974b-5742e60acb05.png)

I don't know if this solves your question.

**Comment by goriunov** [comment]
Sorry for long time no answer, have been working, What if in case i would like to change the size of the container for tablets (like in bootstrap) col-md-, col-sm, col-lg is there any way i can do it?

**Comment by goriunov** [comment]
I think if you add possibility to change sizing of containers in different screen resolutions it would be really good. Because now you have only 2 positions  <480 and  >480 that make it a bit uncomfortable if you i want to change  container size for tablets in 768px or small desktop screens in ~900px

**Comment by jmjuanes** [comment]
Ok, I think that can be a good idea. I will start with the implementation of the grid column sizes for small, medium and large screens.

**Comment by goriunov** [comment]
Hope to see it faster, i really need this kinda thing)

**Comment by jmjuanes** [comment]
The `master` branch has now a compiled version of **siimple** with the grid sizes. I have added the following sizes: 
- `siimple-grid-col-sm--X`: screens < 480px
- `siimple-grid-col-md--X`: screens < 768px
- `siimple-grid-col-lg--X`: screens < 960px
- `siimple-grid-col-xl--X`: screens < 1280px
- `siimple-grid-col--X`: all screen sizes.

Can you try it and give me your feedback, please?

**Comment by goriunov** [comment]
Cool, will check soon )

**Comment by jmjuanes** [comment]
Any updates on this? Otherwise this issue will be closed.

**Comment by jmjuanes** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
