### ISSUE TITLE
Bug with the switch on Chrome using Windows 10

### ISSUE THREAD

**Issue by alextjd** [siimple/siimple#23]
The switch inner element does not totally center vertically. This issue is happening using Google Chrome in Windows 10. Have a quick look at it: 
![image](https://user-images.githubusercontent.com/26857874/33167299-5e796b66-d03d-11e7-80d8-60559051c703.png)

**Comment by chaitanyanettem** [comment]
Hey just wanted to add that this is also happening on Firefox in Ubuntu.

![2017-12-25_20 36 19_288x55](https://user-images.githubusercontent.com/1092783/34340988-c332ee26-e9b3-11e7-9765-dbe7c3732a78.png)

Also tried it in chromium. It looks sort of okay there but still a tiny bit off I think.

![2017-12-25_20 39 18_286x75](https://user-images.githubusercontent.com/1092783/34340994-e492bd26-e9b3-11e7-958c-9aec03148e01.png)

**Comment by jmjuanes** [comment]
Solved! The problem was in the switch background style. Now it works properly in all browsers 🙂 

Thanks @alextjd and @chaitanyanettem
