### ISSUE TITLE
Minor changes for v3.1.0

### ISSUE THREAD

**Issue by jmjuanes** [siimple/siimple#27]
Minor changes to do: 
### Typography
- [x] Change `font-size` to `13px` in `siimple-pre`.
- [x] Change `font-size` to `13px` in `siimple-code`.
- [x] Change `padding` value of `siimple-pre` to `15px`.

### Elements 
- [x] Add `siimple-alert-title` class to create a title in the alert element.

### Layout
- [x] Change the `siimple-menu-item` color to `navy-3` or `navy-4`.
- Change the `siimple-menu-item` height to `30px`. **Under consideration**.
- Change the `siimple-breadcrumb` height to `30px`. **Under consideration**.

### Form 
- [x] `siimple-form-field`: change margin-bottom from `16px` to `15px`.
- [x] `siimple-form-title`: change margin-bottom from `10px` to `20px`.

**Comment by alextjd** [comment]
Suggestion in Form:
- siimple-form-field: change margin-bottom from 16px to 15px.
- siimple-form-title: change margin-bottom from 10px to 20px.
