### ISSUE TITLE
scss/_all.scss importing not exiting files

### ISSUE THREAD

**Issue by jcger** [siimple/siimple#31]
Hi!

I'm using siimple as a dependency of my npm project. I use parcel as bundler and after adding `@import 'siimple/scss/all';` to my main sass file, the bundler fails with:

```
🚨  /Users/julian/project/src/index.scss:22:1: File to import not found or unreadable: ./typography/_list.scss.
Parent style sheet: /Users/julian/project/node_modules/siimple/scss/_all.scss
    at options.error (/Users/julian/project/node_modules/node-sass/lib/index.js:291:26)
```

It looks like files that doesn't exist are being imported and files that do exist, aren't 🤷‍♂️ 

node v9.5.0
npm v5.7.1
siimple v^3.1.0-beta

**Comment by jmjuanes** [comment]
Hello @jcger 

Yes, that's true. Also, the new styles (progress, badge...) added in `3.1.0` are not imported in `_all.scss`. I will fix it right now.

Thanks for your issue and thanks for using `siimple` 😄

**Comment by jmjuanes** [comment]
The new version `v3.1.0-beta.1` is out with the fixes for this issue. Please, check if it works before closing this issue.

Thank you again and I look forward to your answer 😄
