### ISSUE TITLE
A lot of todos for siimplicity

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [siimple/siimple#39]
Let's discuss these topics

* Use [`sass-lint`](https://github.com/sasstools/sass-lint) for static code analyze
  * We need to know which style guide we are using. I found [AirBnB CSS/Sass style guide](https://github.com/airbnb/css)
* Do we need wiki for the main project? I asked because open for edit to everyone.
* I think, we can use default project panel and we can easily collaborate between issues or PRs. Also, it is easy to see who is available for next issue or PRs for review.
* Documentation site needs search box and version options.
* Use dist folder instead under the main repository. My idea is upload dist folder with release. Or we can use both.

/cc @jmjuanes

**Comment by BerkhanBerkdemir** [comment]
Sample screen shot from `sass-lint`
![screenshot from 2018-05-31 17-54-13](https://user-images.githubusercontent.com/24360355/40815485-afabfdde-64fb-11e8-9af0-ce7607a6e8b0.png)

**Comment by BerkhanBerkdemir** [comment]
Oh, I forgot to add the branch that I worked yesterday about lint https://github.com/BerkhanBerkdemir/siimple/commit/55315301167252d1af7659595aaa53acd72acb39. Lint uses AirBnB css/scss style guide.

**Comment by jmjuanes** [comment]
> Use sass-lint for static code analyze

:scream: 3411 warnings!! Yes, we should add `sass-lint` to analyze the code.

> Do we need wiki for the main project?

I think that we don't need the wiki. What do you think?

> I think, we can use default project panel and we can easily collaborate between issues or PRs. Also, it is easy to see who is available for next issue or PRs for review. 

There is a project called `siimple-develop`. I am using it for managing the issues and the PR.

> Documentation site needs search box and version options.

I am finishing the new documentation site. Is on `docs` folder of this repository.

> Use dist folder instead under the main repository. My idea is upload dist folder with release. Or we can use both.

Do you mean when publishing on npm we should only publish `dist` folder? I prefer to publish the main repository, because there are a lot of people that are using the scss files of the release in other projects (me included).

**Comment by BerkhanBerkdemir** [comment]
> :scream: 3411 warnings!! Yes, we should add sass-lint to analyze the code.

I used default sass-lint. That's why we got 3411. Right now we have less than 500 error :laughing:.

> I think that we don't need the wiki. What do you think?

Let's close it or redirect to documentation page.

> There is a project called siimple-develop. I am using it for managing the issues and the PR.

IMO :+1:

> I am finishing the new documentation site. Is on docs folder of this repository.

But question was different :smile:. Will you add search box?

> Do you mean when publishing on npm we should only publish dist folder? I prefer to publish the main repository, because there are a lot of people that are using the scss files of the release in other projects (me included).

I realized that question is bad

**Comment by jmjuanes** [comment]
Yes, I will add the search box. My response was that I am finishing the documentation and some features have not been implemented yet, like the search box (I had it in mind).

**Comment by jmjuanes** [comment]
I have implemented the search in the (new) docs:

![image](https://user-images.githubusercontent.com/5751201/41053732-a7cf294a-69bc-11e8-8838-3f9773419aa9.png)

![image](https://user-images.githubusercontent.com/5751201/41053759-bb8f3f88-69bc-11e8-9f55-77fb8ffb8016.png)

**Comment by BerkhanBerkdemir** [comment]
All I can say. THIS IS AWESOME, @jmjuanes!!! :confetti_ball: :confetti_ball: :confetti_ball: :confetti_ball:

**Comment by 0x92** [comment]
Sexy ^-^

**Comment by BerkhanBerkdemir** [comment]
Can we close this issue if it is done, @jmjuanes?
