### ISSUE TITLE
Error in _grid.scss with Jekyll

### ISSUE THREAD

**Issue by cheshire137** [siimple/siimple#4]
I'm trying to use Siimple's SCSS files in my Jekyll site. I'm importing siimple.scss but I get the following error when I try to run Jekyll:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting '/css/style.scss':
                    Invalid CSS after " width: #{$w}%": expected expression (e.g. 1px, bold), was "; display: inli..." on line 41
jekyll 3.1.2 | Error:  Invalid CSS after "    width: #{$w}%": expected expression (e.g. 1px, bold), was "; display: inli..." on line 41
```

It seems to be having a problem with line 41 of _grid.scss:

```sass
    width: #{$w}%; display: inline-block; vertical-align: top; float: left; padding: 1%;
```

**Comment by jmjuanes** [comment]
Hi @cheshire137.

Thanks for your issue. I think that the problem is with `#{$w}%`. I have updated the `_grid.scss` file. Can you try it and check if now works? Thanks!

**Comment by cheshire137** [comment]
That works, thank you!

**Comment by jmjuanes** [comment]
Sorry, I have found a bug in the correction. I have fixed it, so please use the latest version that I have published (`v1.3.3`).

Check if now works correctly and sorry for the inconvenience.

**Comment by oltmannsdaniel** [comment]
I also have new Column Sizes that match better. I will add them soon

**Comment by cheshire137** [comment]
Ah, I bet that bug you found was the one I was just going to mention: you end up with `width: "72.99%"` instead of `width: 72.99%`. :) Using the latest now, seems good so far!

**Comment by jmjuanes** [comment]
Excellent! Thank you very much for using Siimple 😄
