### ISSUE TITLE
Small Buttons

### ISSUE THREAD

**Issue by HDVinnie** [siimple/siimple#41]
First off I just want to say thank you for your beautiful CSS Framework. Well Done!

I have a suggestion regarding buttons. In my opinion the default buttons are the perfect size for a everyday button. It would however be nice to be able to have a option for a smaller button as well.

```
<div class="siimple-btn siimple-btn-small siimple-btn--purple">My Button</div>
```

```
.siimple-btn.siimple-btn-small {
padding: 0px 10px;
font-size: 12px;
line-height: 20px;
}
```

**Comment by jmjuanes** [comment]
Added new class `siimple-btn--small` to change the button size to small:

![image](https://user-images.githubusercontent.com/5751201/45255350-851b9600-b385-11e8-8c84-679e7c922b3d.png)

Will be available with the new release of **siimple**. Thank you :smile:
