### ISSUE TITLE
Social Media 

### ISSUE THREAD

**Issue by chizom** [siimple/siimple#42]
I am loving this framework. At the same time I really need this plartform to be active on social networks. Especially for the fact that SiimpleCSS is on twitter

We need quick response to questions asked about the framework. I would be willing to learn more on how to use this awesome tool and answer questions on social  networks on how to use specific features. Siimple needs a quick response time on its social media page just as it is lite on the browser

I would be willing to be one of the individuals who end up helping with the social media thingy. 

I am also new to Git, so I would be learning a lot from you. This would be the first project I would be willing to contribute to...

**Comment by jmjuanes** [comment]
Hello @chizom 

Thanks a lot for your kind words about our framework! Yes, we are aware that projects like **siimple** would benefit from quick responses on social media, and this is our aim in a near future. 

We are thankful for your offer. At the moment, we are concentrating all our social media interaction on the Gitter chat and issues posted on GitHub. If you are willing to help, we encourage you to participate in these channels. You are more than welcome to participate in these channels (with questions and answers). We are currently using twitter only for announcements.

Regards,
**The siimple team**
