### ISSUE TITLE
siimple-grid-col-hide

### ISSUE THREAD

**Issue by chizom** [siimple/siimple#43]
I was thinking there should be a class just to hide the col irrespective of the size of the viewing device.

> Do you think I should write a hide class for siimple-grid-col-hide (that would be my first official contribution to the codebase)

**Comment by jmjuanes** [comment]
Hello @chizom Sorry for the big delay :cry: 

Ok, so if you are interested this can be your first contribution. You should fork the repo and add the code for the `siimple-grid-col--hide` class. Then, do a PR to the `develop` branch of **siimple**. 

I will keep this issue open until you make the PR, so if you have any question feel free to ask!

**Comment by jmjuanes** [comment]
Closed due to inactivity. Feel free to reopen if you want to implement this feature.
