### ISSUE TITLE
Having Trouble with Safari

### ISSUE THREAD

**Issue by Tijanwatt** [siimple/siimple#48]
**Describe the bug**
Website I'm building on my localhost does not render correctly using Safari on my imac (MacOs High Sierra 10.13.6 ).  Works fine on chrome.

**To Reproduce**
Building a website using the templates downloaded from the website; i.e. siimple.html and siimple.css.

**Expected behavior**
Fonts and other effects from the css do not appear in the safari browser (fine in chrome).

**Screenshots or Project link**

**Desktop (please complete the following information):**
* MacOs High Sierra 10.13.6  
* Browser Safari 
* Version 11.1.2

**Comment by jmjuanes** [comment]
Hello! Please, I need more information to solve your issue.
- Could you provide screenshots? 
- I don't know where you have downloaded the file `siimple.html`. Could you provide the path of this file in the repository?

**Comment by jmjuanes** [comment]
Perfect! Closing issue.
