### ISSUE TITLE
Sizing tale cells

### ISSUE THREAD

**Issue by yoshikawaa** [siimple/siimple#50]
I want to sizing table cells finely.
For example, add classes `siimple-table-cell--1`~`siimple-table-cell--12` to sizing table cells.

**Comment by jmjuanes** [comment]
Hi @yoshikawaa Thank for your issue and PR. I have merged your PR, sorry for the delay.
I am going to integrate your changes with the `v3.2.0` branch, where we have updated the table for the new version :smile:
