### ISSUE TITLE
Reference site

### ISSUE THREAD

**Issue by icetee** [siimple/siimple#6]
Do you use in [reference](http://siimple.juanes.xyz/reference) site “btn-outline” the new button type and not using like a style.

_How can we use?_

btn btn-outline btn-small OR btn-outline btn-small (no-select doesn't work)

**Comment by jmjuanes** [comment]
Hi @icetee 

The correct way to use small outline buttons is `btn-outline btn-small`. But as you say, `no-select` doesn't work in outline buttons. I forgot to call your `no-select` mixin in `btn-outline`, sorry.

**Comment by jmjuanes** [comment]
Hello @icetee 

First, sorry a lot for the big delay solving your issue. I have published right now the new version of Siimple `v1.3.5` that fixes your issue with the `user-select` on `btn-outline` (https://github.com/siimple/siimple/releases/tag/v1.3.5). 

Thanks a lot :)
