### ISSUE TITLE
Added siimple to Gabo's Awesome CSS Frameworks

### ISSUE THREAD

**Issue by gabrielizalo** [siimple/siimple#66]
Added **siimple** to [**Gabo's Awesome CSS Frameworks**](https://github.com/gabrielizalo/Awesome-CSS-Frameworks) in the _General Purpose_ section.

**Comment by jmjuanes** [comment]
Hello @gabrielizalo thank you!

I wonder if it could be added to the lightweight frameworks section, because the latest version it's 9.4Kb gzipped (https://bundlephobia.com/result?p=siimple@3.3.0).

Anyway, thanks for adding it :smile:

**Comment by gabrielizalo** [comment]
Perfect.. It's done.
;)
