### ISSUE TITLE
Buttons should use semantic Elements

### ISSUE THREAD

**Issue by troxler** [siimple/siimple#68]
**Describe the bug**
The buttons are using `div` elements instead of semantic `input` or `button` elements.

**Expected behavior**
Replace all buttons using `div` elements with either `input` (`type` attribute could be `submit` or `reset`) or `button` elements.

**Desktop (please complete the following information):**
All systems and browsers.

**Smartphone (please complete the following information):**
All systems and browsers.

**Comment by jmjuanes** [comment]
Switched to `<button>` elements in btn documentation instead of `<div>` elements. Thank you!
