### ISSUE TITLE
Import OpenSans

### ISSUE THREAD

**Issue by dohliam** [siimple/siimple#7]
Would it be possible to `@import` OpenSans so that the stylesheet does not fail when this font is not installed on a user's machine? Adding this line at the top of siimple.css solved this issue for me:

    @import url('https://fonts.googleapis.com/css?family=Open+Sans:400,300');

This means I can drop siimple.css into any simple page and not need to change anything else for it to take effect. Of course, it is also possible to do this separately in the header of the page itself, but it seems much cleaner for the stylesheet to be self-contained.

**Comment by jmjuanes** [comment]
Hello @dohliam , I think that is a great idea, and this will made the framework more portable!

**Comment by jmjuanes** [comment]
Now `v1.3.5` fixs your issue (https://github.com/siimple/siimple/releases/tag/v1.3.5) Thanks a lot! :)
