### ISSUE TITLE
Can legacy color be manteined

### ISSUE THREAD

**Issue by Dacker15** [siimple/siimple#77]
I read the documentation and I saw that the support for this color will be dropped soon.
Beacause I use it in my project and I don't want fork the repository to receive package update,
I want to know if it is possible to keep it and realize helper.
If it is not possible, can I know why they will be removed?

Thanks

**Comment by jmjuanes** [comment]
Hello! 

The idea is that legacy colors helpers will be moved to `@siimple/colors` package, and we will keep in the core module only basic colors helpers. Legacy colors modifiers will be removed, and in the core module we will keep only basic colors modifiers (primary, secondary, error, warning and success).

Question: are you using colors helpers (`siimple--color-purple`) or colors modifiers (`siimple-btn--purple`)? Or both?

**Comment by Dacker15** [comment]
Sorry, but I didn't understand very well.
Will legacy color stay available in another package?

**Comment by jmjuanes** [comment]
> Sorry, but I didn't understand very well.

There are two types of color class names: "color helpers" and "color modifiers". 
- Color helpers were introduced in `v3.1.0` and are documented here: https://docs.siimple.xyz/helpers/colors.html . 
- Color modifiers are class names used to change the color of some siimple elements, for example the button or the tip. Color modifiers usually change both background and text color. For example, `siimple-btn--red` will set in the button the background color to red and the text color to white.

> Will legacy color stay available in another package?

Yes and no. Our idea in the `@siimple/colors` package is to keep only the legacy colors (and another new colors) as helpers, so you can change the text color and background color of any html element with `siimple--color-*` and `siimple--bg-*`. 

But in this package will not include class names like `siimple-btn--red` or `siimple-tip--orange`. So the point is that you need to keep these class names for your project. Is that true?

**Comment by Dacker15** [comment]
Thanks for your answer. I only need helpers so if they are available in `@siimple/colors`, it will be ok.
Could I ask you when they will be removed?

**Comment by jmjuanes** [comment]
> Thanks for your answer. I only need helpers so if they are available in @siimple/colors, it will be ok.

Perfect!!

> Could I ask you when they will be removed?

Version `4.0.0` of `@siimple/css` won't include legacy colors. But at this moment I don't know the exact date.

**Comment by Dacker15** [comment]
Thanks for information
